#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2017, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

# snap_delete host:parent_image snap_id vmid ds_id

SRC=$1
SNAP_ID=$2
VMID=$3
DSID=$4
DOMAIN="one-$VMID"

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
    DATASTORES=/var/lib/one/datastores
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
    DATASTORES=$ONE_LOCATION/var/datastores
fi

DRIVER_PATH=$(dirname $0)

. $TMCOMMON

SRC_PATH=$(arg_path $SRC)
SRC_HOST=$(arg_host $SRC)

#-------------------------------------------------------------------------------
# Get Image information
#-------------------------------------------------------------------------------

DISK_ID=$(basename ${SRC} | cut -d. -f2)

XPATH="${DRIVER_PATH}/../../datastore/xpath.rb --stdin"

unset i j XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <(onevm show -x $VMID| $XPATH \
                    /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/SOURCE \
                    /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/CLONE \
                    /VM/STATE)

SNAP_LIST=($(onevm show -x $VMID | sed -n  '/^ *<SNAPSHOT> *$/,/^ *<\/SNAPSHOT>/p' | grep -o '<ID>.*</ID>' | while read line; do echo $line | $XPATH /ID ; done))

DISK_SRC="${XPATH_ELEMENTS[j++]}"
CLONE="${XPATH_ELEMENTS[j++]}"
STATE="${XPATH_ELEMENTS[j++]}"

SYSTEM_DS_PATH=$(dirname ${SRC_PATH})
IMAGE_DS_PATH=$(dirname ${DISK_SRC})

SYSTEM_DS_DISK_PATH_SHORT="disk.${DISK_ID}"
SYSTEM_DS_DISK_PATH="${SYSTEM_DS_PATH}/${SYSTEM_DS_DISK_PATH_SHORT}"

NEXT_SNAP_ID=$(($SNAP_ID+1))

SNAP_DIR="${DISK_PATH}.snap"
SNAP_DIR_SHORT="disk.${DISK_ID}.snap"

SNAP_PATH="${SNAP_DIR}/${SNAP_ID}"
SNAP_PATH_SHORT="${SNAP_DIR_SHORT}/${SNAP_ID}"

NEXT_SNAP_PATH="${SNAP_DIR}/${NEXT_SNAP_ID}"
NEXT_SNAP_PATH_SHORT="${SNAP_DIR_SHORT}/${NEXT_SNAP_ID}"

#-------------------------------------------------------------------------------
# Online mode
#-------------------------------------------------------------------------------

ONLINE_CMD=$(cat <<EOT
set -ex -o pipefail

    SNAP_PATH=\$(virsh dumpxml $DOMAIN | xmlstarlet sel -t -v "//*/source/@file" | grep "$SNAP_PATH_SHORT\$")
    NEXT_SNAP_PATH=\$(virsh dumpxml $DOMAIN | xmlstarlet sel -t -v "//*/source/@file" | grep "$NEXT_SNAP_PATH_SHORT\$")
    DISK_PATH=\$(virsh dumpxml $DOMAIN | xmlstarlet sel -t -v "/domain/devices/disk[.//@file='\${SNAP_PATH}']/source/@file")
    
    NEXT_SNAP_BASE=\$(virsh dumpxml $DOMAIN | xmlstarlet sel -t -v "//*[source/@file='\${NEXT_SNAP_PATH}']/backingStore/source/@file")
    NEXT_SNAP_BASE_SHORT=\$(echo \$NEXT_SNAP_BASE | awk -F "${SYSTEM_DS_DISK_PATH_SHORT}" '{print "${SYSTEM_DS_DISK_PATH_SHORT}" \$NF}')
    
    if ! [[ "${SNAP_LIST[@]} " =~ " ${NEXT_SNAP_ID} " ]]; then
    
        if [ "\$NEXT_SNAP_PATH" == "\$DISK_PATH" ]; then
            virsh blockcommit $DOMAIN --path "\${DISK_PATH}" --top "\${NEXT_SNAP_PATH}" --base "\${NEXT_SNAP_BASE}" --active --wait --pivot
        else
            virsh blockcommit $DOMAIN --path "\${DISK_PATH}" --top "\${NEXT_SNAP_PATH}" --base "\${NEXT_SNAP_BASE}" --wait
        fi
    
        if [ "\$?" == "0" ]; then
            NEW_DISK_PATH=\$(virsh dumpxml $DOMAIN | xmlstarlet sel -t -v "/domain/devices/disk[.//@file='\${NEXT_SNAP_BASE}']/source/@file")
            NEW_DISK_PATH_SHORT=\$(echo \$NEW_DISK_PATH | awk -F "${SYSTEM_DS_DISK_PATH_SHORT}" '{print "${SYSTEM_DS_DISK_PATH_SHORT}" \$NF}')
            rm -f \${NEXT_SNAP_PATH}
            ln -sf "\${NEW_DISK_PATH_SHORT}" "${SYSTEM_DS_DISK_PATH}"
        fi
    
    fi

EOT
)

#-------------------------------------------------------------------------------
# Offline mode
#-------------------------------------------------------------------------------

OFFLINE_CMD=$(cat <<EOT
set -ex -o pipefail

PREVIOUS_SNAP="${SYSTEM_DS_PATH}/\$(readlink $SYSTEM_DS_DISK_PATH)"
if [ ! -f "\$PREVIOUS_SNAP" ]; then
    PREVIOUS_SNAP=\$(readlink -f $SYSTEM_DS_DISK_PATH)
fi

cd "${SNAP_DIR}"
qemu-img commit "${SNAP_PATH}" 

EOT
)

#-------------------------------------------------------------------------------


if ! [[ $STATE -gt 0 ]]; then
   log "Error deleting snapshot: Wrong STATE! $STATE"
   exit 1
fi

echo "STATE=$STATE" >> /tmp/123

if [[ $STATE -eq 3 ]]; then
    ssh_exec_and_log "${SRC_HOST}" "${ONLINE_CMD}" \
                     "Error deleting snapshot ${SNAP_PATH}"
else
    ssh_exec_and_log "${SRC_HOST}" "${OFFLINE_CMD}" \
                     "Error deleting snapshot ${SNAP_PATH}"
fi


